### ISSUE TITLE
Query Elasticsearch for data

### ISSUE THREAD

**Issue by alex855k** [CSProjectsEAL/GraBID#26]
## 📋 User story
As a user I want to be able to query for specific data, so I can get an insight on what is being stored in Elasticsearch.

## Description
As a user I want to obtain some data that doesn't belong to a dashboard element, therefore I write a query to be sent to Elasticsearch Web API, getting the data returned from it.

## Prerequisite
- [x] Elasticsearch service is implemented.

#### Mainflow:
- [x] Open query page
- [x] Select a preset query
- [x] Edit values in the preset query 
- [x] Press _send_ button

**Comment by alex855k** [comment]
## 📋 User story
As a user I want to be able to view a dashboard so I can decide on what actions to perform on it.

## Description
As a user I want a page where I can decide what so I can decide on what actions to perform on it. Planned actions that extends this user stories are edit dashboard, delete dashboard and dashboard viewing mode

## Prerequisite
- [ ] Select dashboard from a list of dashboards #22

## Acceptance Criteria
#### Mainflow:
- [ ] From the sidebar menu the user will be able to select an icon that will open a menu for viewing a list of dashboard names.
- [ ] When the user hover over the dashboard name, after 0.5s a description dashboard in a box from the point of origin of the mouse. So that I can more information about the dashboard.
- [ ] When pressing a dashboard name I will be sent to a dashboard view component page.

**Comment by davi7725** [comment]
PR: #CSProjectsEAL/GraBID-Dashboard/pull/3
