### ISSUE TITLE
View dashboard

### ISSUE THREAD

**Issue by alex855k** [CSProjectsEAL/GraBID#32]
## 📋 User story
As a user I want to be able to view a dashboard so I can analyze the data presented by it.

## Description
As a user I want a page that allows me to view all the dashboard elements present in a specific dashboard. Action that extend this user story is edit dashboard.

## Prerequisite
- [ ] A dashboard exists.

#### Mainflow:
1. [ ] Expand menu.
1. [ ] Click dashboard
1. [ ] Select dashboard from a list of dashboard
1. [ ] Redirection to '404' page happens if the dashboard no longer exists

**Comment by alex855k** [comment]
## 📋 User story
As a user I want to be able to view a dashboard so I can decide on what actions to perform on it.

## Description
As a user I want a page where I can decide what so I can decide on what actions to perform on it. Planned actions that extends this user stories are edit dashboard, delete dashboard and dashboard viewing mode

## Prerequisite
- [ ] Select dashboard from a list of dashboards #22

## Acceptance Criteria
#### Mainflow:
- [ ] From the sidebar menu the user will be able to select an icon that will open a menu for viewing a list of dashboard names.
- [ ] When the user hover over the dashboard name, after 0.5s a description dashboard in a box from the point of origin of the mouse. So that I can more information about the dashboard.
- [ ] When pressing a dashboard name I will be sent to a dashboard view component page.

**Comment by elit0451** [comment]
PR: https://github.com/CSProjectsEAL/GraBID-Dashboard/pull/4

**Comment by elit0451** [comment]
PR for inexistent dashboard: https://github.com/CSProjectsEAL/GraBID-Dashboard/pull/5
