### ISSUE TITLE
Implement Angular framework

### ISSUE THREAD

**Issue by elit0451** [CSProjectsEAL/GraBID#43]
## 📋 Epic
Implement Angular framework as part of our web application frontend in a .net core framework.

## Description
Using the Angular framework, we should be able to implement all the CRUD operations on a dashboard and its elements, as well as query component to request information from Elasticsearch directly. In addition, an Elasticsearch service would be implemented to facilitate the connection to its(Elasticsearch) backend API.

## List of requirements
- [x] Create markups _/parent of #42/_ 

## Acceptance Criteria
1. Elasticsearch service (request the latest info from Elasticsearch API)     _/parent of #44/_
1. Create a new dashboard     _/parent of #39/_ 
1. Edit a dashboard     _/parent of #23/_ 
1. Create a dashboard element     _/parent of #29/_
1. Edit a dashboard element     _/parent of #36/_
1. View a dashboard     _/parent of #32/_ 
1. Delete a dashboard     _/parent of #34/_
1. Rearrange dashboard elements     _/parent of #28/_
1. Delete a dashboard element     _/parent of #31/_
1. Query component     _/parent of #26/_

**Comment by davi7725** [comment]
Everything's done
